#!/bin/bash
# The script for centos 7 minimal environment
# author: Jack
# v1.02

if [ "$UID" -ne 0 ];then
	echo "must be run by root!"
	exit
fi

if [ "$#" -ne 1 ];then
	echo "Usage: $0 <package_name>"
	exit
fi


if [ -z `rpm -qa | grep epel-release` ];then
	yum install epel-release -y
fi


install_dep(){
	yum -y install unzip ntp wget rsync gcc gcc-c++ make autoconf libmcrypt libmcrypt-devel mcrypt mhash libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel libxml2 libxml2-devel zlib zlib-devel glibc glibc-devel glib2 glib2-devel bzip2 bzip2-devel ncurses ncurses-devel curl curl-devel e2fsprogs e2fsprogs-devel krb5-devel libidn libidn-devel openssl openssl-devel libtool libtool-libs libevent-devel libevent openldap openldap-devel openldap-clients openldap-servers libtool-ltdl libtool-ltdl-devel bison bison-devel cloog-ppl ppl libmemcached-devel expat-devel gettext-devel gd-devel mhash-devel pcre-devel screen boost boost-devel gperf libevent libevent-devel uuid-devel libuuid libuuid-devel uuid cmake geoip geoip-devel jemalloc jemalloc-devel tcl perl-ExtUtils-Embed

	if [ "$?" -eq 0 ];then
		echo "install dependent ... ok."
	else
		exit 1
	fi
}

install_mysql(){
if [ ! -d /usr/local/lnmp/mysql ];then
	echo "download mysql ..."
	if [ ! -f ./mysql-5.6.26.tar.gz ];then
		# wget http://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-boost-5.7.15.tar.gz
		wget http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.26.tar.gz
	fi
	echo "decompression ..."
	tar zxf mysql-5.6.26.tar.gz
	cd mysql-5.6.26
	echo "compile phase ..."
	cmake \
	-DCMAKE_INSTALL_PREFIX=/usr/local/lnmp/mysql \
	-DMYSQL_DATADIR=/data/db/mysql/var \
	-DSYSCONFDIR=/etc \
	-DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
	-DMYSQL_TCP_PORT=3306 \
	-DDEFAULT_CHARSET=utf8 \
	-DDEFAULT_COLLATION=utf8_general_ci \
	-DEXTRA_CHARSETS=all \
	-DDOWNLOAD_BOOST=1 \
	-DWITH_BOOST=/usr/local/lnmp/boost
	if [ "$?" -eq 0 ];then
		make -j 4 && make install
	fi

	if [ ! `cat /etc/group | awk -F: '{print $1}'| grep mysql` ];then
		groupadd mysql
	fi
	if [ ! `cat /etc/passwd | awk -F: '{print $1}'| grep mysql` ];then
		useradd -M -g mysql -s /sbin/nologin mysql
	fi

	cp ../profile.d/mysql.sh /etc/profile.d/
	echo "/usr/local/mysql/lib" > /etc/ld.so.conf.d/mysql.conf
	ldconfig
	source /etc/profile.d/mysql.sh
	echo
	echo "init ..."
	echo
	mkdir -p /data/db/mysql/var
	chown -R mysql:mysql /data/db/mysql/var
	if [ -f /etc/my.cnf ];then
		rm -rf /etc/my.cnf
	fi
	# /usr/local/lnmp/mysql/bin/mysqld --user=mysql --basedir=/usr/local/lnmp/mysql --datadir=/data/db/mysql/var/ --explicit_defaults_for_timestamp --initialize --initialize-insecure
	/usr/local/lnmp/mysql/scripts/mysql_install_db --user=mysql --basedir=/usr/local/lnmp/mysql --datadir=/data/db/mysql/var --explicit_defaults_for_times
	cp  ../init/mysqld.service  /usr/lib/systemd/system/mysqld.service
	cp ../conf/my.cnf /etc/
        cp ../logrotate/mysql /etc/logrotate.d/
	mkdir /data/db/mysql_binlog
	mkdir /data/db/mysql/logs
	chown -R mysql.mysql /data/db/mysql/logs
	chown -R mysql.mysql /data/db/mysql_binlog
	#systemctl start mysqld.service
else
		echo "mysql directory is exist. will be quit"
		exit 0
fi
}

install_php(){
if [ -d "/usr/local/lnmp/php56" ];then
	echo "php directory is exist."
	exit 0
else
	if [ ! -f ./php-5.6.12.tar.gz ];then
		echo "download php ..."
		wget http://cn.php.net/get/php-5.6.12.tar.gz/from/this/mirror -O php-5.6.12.tar.gz
	fi
	echo "decompression ..."
	tar zxf php-5.6.12.tar.gz
	echo "compile phase ..."
	ln -s /usr/lib64/libldap* /usr/lib/
	ln -s /usr/lib64/libexpat* /usr/lib/
	ln -s /usr/lib64/liblber-2.4.so.2 /usr/lib/
        ln -s /usr/lib64/liblber.so /usr/lib/
	cd php-5.6.12
	./configure --prefix=/usr/local/lnmp/php56 \
	--with-zlib --with-mysql=mysqlnd --with-mysqli=mysqlnd \
	--with-pdo-mysql=mysqlnd --with-jpeg-dir --with-png-dir --with-freetype-dir \
	--with-libexpat-dir --with-libxml-dir --with-gd --with-openssl --with-iconv \
	--with-gettext --with-curl --with-mhash --enable-pcntl --with-mcrypt --with-bz2 \
	--with-ldap --enable-ftp --with-ldap-sasl --enable-gd-native-ttf \
	--enable-mbstring=all --enable-xml --enable-pdo --enable-exif --enable-mbregex \
	--enable-zip --enable-soap --enable-sockets --enable-bcmath --enable-shmop \
	--enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-inline-optimization \
	--disable-xmlreader --disable-debug --disable-rpath --without-pear \
	--enable-fpm --with-fpm-user=nobody --with-fpm-group=nobody --enable-opcache

	if [ "$?" -eq 0 ];then
		make && make install
	else
		exit 1
	fi
	cp php.ini-production /usr/local/lnmp/php56/lib/php.ini
	cp -rf ../init/php-fpm.service /usr/lib/systemd/system/
	cp /usr/local/lnmp/php56/etc/php-fpm.conf.default /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;pid = run\/php-fpm.pid/pid = run\/php-fpm.pid/' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;error_log = log\/php-fpm.log/error_log = log\/php-fpm.log/' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;daemonize = yes/daemonize = yes/' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's#listen = 127.0.0.1:9000#listen = /usr/local/lnmp/php56/var/run/php-fpm.sock#' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;listen.owner = nobody/listen.owner = nobody/' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;listen.group = nobody/listen.group = nobody/' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed -i 's/;pm.max_requests = 500/pm.max_requests = 500/' /usr/local/lnmp/php56/etc/php-fpm.conf
	sed '/; extension_dir = "ext"/ a\extension_dir = "/usr/local/lnmp/php56/lib/php/extensions/no-debug-non-zts-20131226"\n\nzend_extension =opcache.so\nopcache.enable=1\nopcache.memory_consumption = 64\nopcache.interned_strings_buffer = 8\nopcache.max_accelerated_files = 4000\nopcache.revalidate_freq = 60\nopcache.fast_shutdown = 1\nopcache.enable_cli = 1\n' -i /usr/local/lnmp/php56/lib/php.ini
	sed -i 's#expose_php = On#expose_php = Off#' /usr/local/lnmp/php56/lib/php.ini
	sed -i 's#short_open_tag = Off#short_open_tag = On#' /usr/local/lnmp/php56/lib/php.ini
	sed -i 's#;cgi.fix_pathinfo=1#cgi.fix_pathinfo=0#' /usr/local/lnmp/php56/lib/php.ini
	sed -i 's#;always_populate_raw_post_data = -1#always_populate_raw_post_data = -1#' /usr/local/lnmp/php56/lib/php.ini
	systemctl start php-fpm.service
	cp -rf ../profile.d/php.sh /etc/profile.d/
	cp ../logrotate/php-fpm /etc/logrotate.d/
	source /etc/profile.d/php.sh
fi
}

php_ext(){
	if [ ! -e ./igbinary-1.2.1.tgz ];then
        	wget http://pecl.php.net/get/igbinary-1.2.1.tgz
        fi
        tar zxvf igbinary-1.2.1.tgz
        cd igbinary-1.2.1
	/usr/local/lnmp/php56/bin/phpize
	./configure  --enable-igbinary --with-php-config=/usr/local/lnmp/php56/bin/php-config
        if [ $? -eq 0 ];then
        	make && make install && cd ..
        else
		exit 1
	fi

	if [ ! -e ./php-mongo-1.6.10.tgz ];then
		wget http://pecl.php.net/get/mongo-1.6.10.tgz -O php-mongo-1.6.10.tgz
	fi
	tar zxvf php-mongo-1.6.10.tgz
	cd mongo-1.6.10/
	/usr/local/lnmp/php56/bin/phpize
	./configure --with-php-config=/usr/local/lnmp/php56/bin/php-config --enable-mongo
	if [ "$?" -eq 0 ];then
		make && make install && cd ..
	else
		exit 1
	fi

	if [ ! -e ./php-redis-2.2.7.tgz ];then
		wget http://pecl.php.net/get/redis-2.2.7.tgz -O php-redis-2.2.7.tgz
	fi
	tar zxvf php-redis-2.2.7.tgz
	cd redis-2.2.7
	/usr/local/lnmp/php56/bin/phpize
	./configure --with-php-config=/usr/local/lnmp/php56/bin/php-config --enable-redis --enable-redis-igbinary
	if [ "$?" -eq 0 ];then
		make && make install && cd ..
	else
		exit 1
	fi

	if [ ! -e ./php-memcache-2.2.7.tgz ];then
		wget http://pecl.php.net/get/memcache-2.2.7.tgz -O php-memcache-2.2.7.tgz
	fi
	tar zxvf php-memcache-2.2.7.tgz
	cd memcache-2.2.7/
	/usr/local/lnmp/php56/bin/phpize
	./configure --with-php-config=/usr/local/lnmp/php56/bin/php-config  --enable-memcache
	if [ "$?" -eq 0 ];then
		make && make install && cd ..
	else
		exit 1
	fi

	sed '/opcache.enable_cli = 1/ a\[mongo]\nextension = mongo.so\n[redis]\nextension = redis.so\n[memcache]\nextension = memcache.so\n[igbinary]\nextension = igbinary.so' -i /usr/local/lnmp/php56/lib/php.ini
	systemctl restart php-fpm.service

}

install_redis(){
if [ -d /usr/local/lnmp/redis ];then
	echo "redis directory is exist."
else
	if [ ! -e './redis-3.2.3.tar.gz' ];then
		wget http://download.redis.io/releases/redis-3.2.3.tar.gz
	fi
	echo "install redis ..."
	tar zxvf redis-3.2.3.tar.gz
	cd redis-3.2.3
	make
	make test
	if [ "$?" -eq 0 ];then
		mkdir -p /usr/local/lnmp/redis/{bin,conf,sbin,run}
		cd src
		cp redis-benchmark redis-check-aof redis-check-rdb redis-cli redis-sentinel redis-trib.rb mkreleasehdr.sh /usr/local/lnmp/redis/bin/
		cp redis-server /usr/local/lnmp/redis/sbin
		cd ..
		cp redis.conf /usr/local/lnmp/redis/conf/redis.conf
		mkdir -p /data/logs/redis_logs
		mkdir -p /data/db/redis/data
		cp ../init/redis.service /usr/lib/systemd/system/
		sed -i 's/daemonize no/daemonize yes/' /usr/local/lnmp/redis/conf/redis.conf
		sed -i 's#pidfile /var/run/redis.pid#pidfile /usr/local/lnmp/redis/run/redis_6379.pid#' /usr/local/lnmp/redis/conf/redis.conf
		sed -i 's#logfile ""#logfile "/data/logs/redis_logs/redis.log"#' /usr/local/lnmp/redis/conf/redis.conf
		sed -i 's#dbfilename dump.rdb#dbfilename data.rdb#' /usr/local/lnmp/redis/conf/redis.conf
		sed -i 's#dir ./#dir /data/db/redis/data#' /usr/local/lnmp/redis/conf/redis.conf
		if [ -s /etc/sysctl.conf ];then
			sed -i '$a\vm.overcommit_memory=1' /etc/sysctl.conf
			sed -i '$a\net.core.somaxconn=10000' /etc/sysctl.conf
		else
			echo -n 'vm.overcommit_memory=1' > /etc/sysctl.conf
			sed -i '$a\net.core.somaxconn=10000' /etc/sysctl.conf
		fi
		sed -i '$a\if test -f /sys/kernel/mm/transparent_hugepage/enabled; then\n    echo never > /sys/kernel/mm/transparent_hugepage/enabled\nfi\n\nif test -f /sys/kernel/mm/transparent_hugepage/defrag; then\n    echo never > /sys/kernel/mm/transparent_hugepage/defrag\nfi\n' /etc/rc.d/rc.local
		systemctl start redis.service
		cp ../profile.d/redis.sh /etc/profile.d/
		source /etc/profile.d/redis.sh
	else
		exit 1
	fi
fi
}

# mongo for centos 6.x
install_mongo(){
if [ -d "/usr/local/lnmp/mongo" ];then
	echo "mongo directory is exist."
else
	echo "install mongo ..."
	if [ ! -e "./mongodb-linux-x86_64-3.0.6.tgz" ];then
		wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.6.tgz
	fi
	tar zxvf mongodb-linux-x86_64-3.0.6.tgz
	mv mongodb-linux-x86_64-3.0.6 /data/lnmp/mongo
	mkdir /usr/local/lnmp/mongo/{conf,data,logs}
	cp init/mongod /etc/init.d/mongod
	chmod a+x /etc/init.d/mongod
	cp conf/mongod.conf /usr/local/lnmp/mongo/conf
	cp profile.d/mongo.sh /etc/profile.d/
	if [ ! `cat /etc/passwd | awk -F: '{print $1}'| grep mongod` ];then
		groupadd mongod && useradd -M -g mongod -s /sbin/nologin mongod
	fi
	chown -R mongod. /usr/local/lnmp/mongo/logs
	chown -R mongod. /usr/local/lnmp/mongo/data
	sed -i '$a\if test -f /sys/kernel/mm/transparent_hugepage/enabled; then\n    echo never > /sys/kernel/mm/transparent_hugepage/enabled\nfi\n\nif test -f /sys/kernel/mm/transparent_hugepage/defrag; then\n    echo never > /sys/kernel/mm/transparent_hugepage/defrag\nfi\n' /etc/rc.d/rc.local
	/etc/init.d/mongod start
	chkconfig --add mongod
	chkconfig mongod on
fi
}

install_jdk()
{
if [ -d "/usr/local/lnmp/jdk1.7.0_79" ];then
	echo "jdk1.7.0_79 directory is exist."
	exit 0
else
	echo "install jdk now ..."
	if [ ! -e "./jdk-7u79-linux-x64.tar.gz"];then
		echo "Please Manual Download"
		exit 1
	else
		tar zxf jdk-7u79-linux-x64.tar.gz
		if [ "$?" -eq 0 ];then
			mv jdk1.7.0_79 /usr/local/lnmp/
			cp profile.d/jdk.sh /etc/profile.d/
			source /etc/profile.d/jdk.sh
		fi
	fi
fi
}

install_tomcat()
{
if [ -d "/usr/local/lnmp/tomcat6" ];then
	echo "tomcat6 directory is exist."
	exit 0
else
	if [ ! -e "./apache-tomcat-6.0.47.tar.gz" ];then
		wget http://apache.tt.co.kr/tomcat/tomcat-6/v6.0.47/bin/apache-tomcat-6.0.47.tar.gz
	fi

	tar zxf apache-tomcat-6.0.47.tar.gz
	mv apache-tomcat-6.0.47 /usr/local/lnmp/tomcat6
	cp init/tomcat.service /usr/lib/systemd/system/
	sed -i 's#CATALINA_OUT="$CATALINA_BASE"/logs/catalina.out#CATALINA_OUT=/data/logs/tomcat_logs/catalina.out#' /usr/local/lnmp/tomcat6/bin/catalina.sh
	mkdir -p /data/logs/tomcat_logs
	cp logrotate/tomcat /etc/logrotate.d/
	systemctl start tomcat.service
	if [ "$?" -eq 0 ];then
		echo "tomcat install success."
		exit 0
	else
		echo "tomcat start failed."
		exit 1
	fi
fi

}

install_nginx(){
if [ -d /usr/local/lnmp/nginx ];then
	echo "nginx directory is exist."
else
	if [ ! `ls ./nginx-1.8.1.tar.gz` ];then
		wget http://nginx.org/download/nginx-1.8.1.tar.gz
	fi
	tar zxvf nginx-1.8.1.tar.gz
	cd nginx-1.8.1
	echo "install nginx ..."
	./configure --prefix=/usr/local/lnmp/nginx --user=nobody \
	--group=nobody --with-ld-opt=-ljemalloc --with-http_ssl_module \
	--with-http_addition_module --with-http_sub_module --with-http_dav_module \
	--with-http_flv_module --with-http_gzip_static_module --with-http_stub_status_module \
	--with-mail --with-mail_ssl_module --with-http_geoip_module \
	--with-http_realip_module

	if [ "$?" -eq 0 ];then
		make && make install
	else
		exit 1
	fi
	cp ../init/nginx.service /usr/lib/systemd/system/nginx.service
	mv /usr/local/lnmp/nginx/conf/nginx.conf /usr/local/lnmp/nginx/conf/nginx.conf.old
	cp ../conf/nginx.conf /usr/local/lnmp/nginx/conf
	/bin/cp -rf ../conf/vhosts /usr/local/lnmp/nginx/conf/
	cp ../logrotate/nginx /etc/logrotate.d/
	systemctl start nginx.service
fi
}
install_memcached(){
	if [ -d /usr/local/lnmp/memcached ];then
		echo "memcached directory is exist."
	else
		if [ ! `ls ./memcached-1.4.24.tar.gz` ];then
			wget http://www.memcached.org/files/memcached-1.4.24.tar.gz
		fi
		tar zxvf memcached-1.4.24.tar.gz
		cd memcached-1.4.24
		echo "install memcache ..."
		./configure --prefix=/usr/local/lnmp/memcached
		if [ "$?" -eq 0 ];then
			make && make install
		else
			exit 1
		fi
		cp ../init/memcached /etc/sysconfig/
		cp ../init/memcached.service /usr/lib/systemd/system/
		mkdir -p /usr/local/lnmp/memcached/lock/subsys/
		mkdir /usr/local/lnmp/memcached/run
		#/etc/init.d/memcached start
		groupadd memcached
		useradd -M -g memcached -s /sbin/nologin memcached
		systemctl daemon-reload
		systemctl start memcached.service
	fi		
}
set_ulimit(){
	sed '/#@student        -       maxlogins       4/a\@users\tsoft\tnofile\t100001\n@users\thard\tnofile\t100002\n@root\tsoft\tnofile\t100001\n@root\thard\tnofile\t100002\n' -i /etc/security/limits.conf
	sed '/*/s/^/#/' -i /etc/security/limits.d/20-nproc.conf
	sed '/root/s/^/#/' -i /etc/security/limits.d/20-nproc.conf
	echo $'# Added by jack\n*	hard	nofile	1000000' > /etc/security/limits.d/80-nproc.conf
}


set_sysctl(){
	sed '$a\vm.swappiness = 0\nvm.overcommit_memory = 1\nnet.core.somaxconn = 512\nnet.ipv4.tcp_tw_reuse = 1\nnet.ipv4.tcp_tw_recycle = 1\nnet.ipv4.tcp_fin_timeout = 30\nnet.ipv4.tcp_keepalive_time = 1200\nnet.ipv4.ip_local_port_range = 1024 65535\nnet.ipv4.tcp_max_syn_backlog = 4096\nnet.ipv4.tcp_max_tw_buckets = 5000\nnet.ipv4.tcp_synack_retries = 2\nnet.ipv6.conf.default.disable_ipv6 = 1\nnet.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv4.conf.default.arp_announce = 2\nnet.core.wmem_max = 873200\nnet.core.rmem_max = 873200\nnet.ipv4.tcp_wmem = 8192 436600 873200\nnet.ipv4.tcp_rmem = 32768 436600 873200\nnet.ipv4.tcp_mem = 786432 1048576 1572864\nnet.ipv4.tcp_retries2 = 5\n' -i /etc/sysctl.conf
	sysctl -p
}

set_ntp(){
	yum install ntp -y
	sed -i 's/server 0.centos.pool.ntp.org iburst/#server 0.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i 's/server 1.centos.pool.ntp.org iburst/#server 1.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i 's/server 2.centos.pool.ntp.org iburst/#server 2.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i 's/server 3.centos.pool.ntp.org iburst/#server 3.centos.pool.ntp.org iburst/' /etc/ntp.conf
	sed -i '/#server 3.centos.pool.ntp.org iburst/a\server 0.th.pool.ntp.org\nserver 1.asia.pool.ntp.org\nserver 2.asia.pool.ntp.org\n' /etc/ntp.conf
	systemctl start ntpd
	ntpdate
}

case "$1" in
	dep)
	install_dep
	;;
	nginx)
	install_nginx
	;;
	ulimit)
	set_ulimit
	;;
	mysql)
	install_mysql
	;;
	php)
	install_php
	;;
	redis)
	install_redis
	;;
	mongo)
	install_mongo
	;;
	php-ext)
	php_ext
	;;
	sysctl)
	set_sysctl
	;;
	ntp)
	set_ntp
	;;
	memcached)
	install_memcached
	;;
	jdk)
	install_jdk
	;;
	tomcat)
	install_tomcat
	;;
	*)
	echo "error flag!"
	;;
esac
