#!/bin/bash

set -e

usage() {
    echo "$0 usage: -b BASEDIR:mysql-install-directory -d DATADIR:mysql-data-directory -v VERSION:mysql-version"
}
while getopts :b:d:v: OPTION;do
    case $OPTION in
        b) BASEDIR=${OPTARG};;
        d) DATADIR=${OPTARG};;
        v) VERSION=${OPTARG};;
        *|h) usage
        exit 1;;
    esac
done

check_user_exists()
{
    if id "$1" > /dev/null 2>&1; then
        echo "$1 exists."
    else
        useradd -M -s /sbin/nologin $1
    fi
}

if [ "$#" -lt 6 ];then
    usage
    exit 1
fi

# dirName=$(echo $1 | sed 's/\/$//g')

if [ ! -d "${BASEDIR}" ];then
#    read -p "directory not found create it [Y|N]: " confirm
#    if [ ${confirm} == 'Y' ] || [ ${confirm} == 'y' ] || [ ${confirm} == 'yes' ];then
       mkdir -p ${BASEDIR}
#    fi
else
   echo "MySQL baseDir already will exist."
fi

if [ "${UID}" -ne 0 ];then
    echo "${UID}"
    echo "not root user"
    exit 1
fi

if ! test -e mysql-${VERSION}.tar.gz;then
    # wget https://downloads.mysql.com/archives/get/p/23/file/mysql-5.7.29.tar.gz
    echo "Donwload First"
    exit 1
fi

if ! test -e boost_1_59_0.tar.gz;then
    wget https://sourceforge.mirrorservice.org/b/bo/boost/boost/1.59.0/boost_1_59_0.tar.gz
fi

if test -d "${BASEDIR}"/boost_1_59_0;then
    :
else
    tar zxf boost_1_59_0.tar.gz -C "${BASEDIR}"
fi


if test -d ${BASEDIR}/bin; then
    echo "${BASEDIR}/bin is not empty!"
    exit 1
else
    if ! test -d ./mysql-${VERSION};then
        tar zxvf mysql-${VERSION}.tar.gz
    fi
    cd mysql-${VERSION}
    cmake \
    -DCMAKE_INSTALL_PREFIX=${BASEDIR} \
    -DMYSQL_DATADIR=/${DATADIR} \
    -DSYSCONFDIR=/etc \
    -DMYSQL_TCP_PORT=3306 \
    -DDEFAULT_CHARSET=utf8 \
    -DDEFAULT_COLLATION=utf8_general_ci \
    -DDEFAULT_COLLATION=utf8_general_ci \
    -DDOWNLOAD_BOOST=1 \
    -DWITH_BOOST=${BASEDIR}/boost_1_59_0
    if [ $? -eq 0 ];then
        make -j2 && make install
    else
        exit 1
    fi
fi

check_user_exists mysql

cat > /etc/profile.d/mysql.sh << EOF
export MYSQL_HOME=${BASEDIR}
export PATH=\$MYSQL_HOME/bin:\$PATH
EOF

echo "${BASEDIR}/lib" > /etc/ld.so.conf.d/mysql.conf

cat > /usr/lib/systemd/system/mysqld.service << EOF
[Unit]
Description=MySQL Community Server
After=network.target
After=syslog.target
[Install]
WantedBy=multi-user.target
[Service]
User=mysql
Group=mysql
PIDFile=${DATADIR}/mysql.pid
PermissionsStartOnly=true
ExecStart=${BASEDIR}/bin/mysqld --defaults-file=/etc/my.cnf
LimitNOFILE=65535
TimeoutSec=600
Restart=always
RestartPreventExitStatus=1
PrivateTmp=false
EOF


if ! test -d ${DATADIR};then
    mkdir -p ${DATADIR}
fi

if ! test -d ${BASEDIR}/logs;then
    mkdir -p ${BASEDIR}/logs
fi

if ! test -d ${BASEDIR}/logs/mysql_binlog;then
    mkdir -p ${BASEDIR}/logs/mysql_binlog
fi

chown -R mysql. ${DATADIR}
chown -R mysql. ${BASEDIR}/logs

systemctl enable mysqld
systemctl start mysqld

# init mysql
if test -d ${DATADIR};then
    ${BASEDIR}/bin/mysqld  \
    --initialize-insecure --user=mysql \
    --basedir=${BASEDIR} \
    --datadir=${DATADIR} \
    --explicit_defaults_for_timestamp
    if [ $? -eq 0 ];then
        echo "init done!"
    else
        exit 1
    fi
else
    echo "not found var directory!"
    exit 1
fi

cat > /etc/my.cnf << EOF
[mysql]
# CLIENT #
port                           = 3306
socket                         = ${DATADIR}/mysql.sock
[mysqld]
# GENERAL #
user                           = mysql
default-storage-engine         = InnoDB
socket                         = ${DATADIR}/mysql.sock
pid-file                       = ${DATADIR}/mysql.pid
explicit_defaults_for_timestamp = 1
skip-innodb		       = 1
# MyISAM #
key-buffer-size                = 64M
# myisam-recover                 = FORCE,BACKUP
# SAFETY #
max-allowed-packet             = 32M
max-connect-errors             = 1000000
skip-name-resolve
sql-mode                       = STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE
sysdate-is-now                 = 1
innodb                         = FORCE
# DATA STORAGE #
datadir                        = ${DATADIR}
# BINARY LOGGING #
log-bin                        = ${BASEDIR}/logs/mysql_binlog/mysql-bin
expire-logs-days               = 7
sync-binlog                    = 1
# Gtid replication #
server-id                      = 1
binlog-format                  = ROW
# CACHES AND LIMITS #
tmp-table-size                 = 32M
max-heap-table-size            = 32M
query-cache-type               = 0
query-cache-size               = 0
max-connections                = 2000
thread-cache-size              = 100
open-files-limit               = 65535
table-definition-cache         = 4096
table-open-cache               = 10240
# INNODB #
innodb-flush-method            = O_DIRECT
innodb-log-files-in-group      = 2
innodb-log-file-size           = 256M
innodb-flush-log-at-trx-commit = 1
innodb-file-per-table          = 1
innodb-buffer-pool-size        = 1G
# LOGGING #
log-error                      = ${BASEDIR}/logs/mysql-error.log
log-queries-not-using-indexes  = 0
slow-query-log                 = 1
long-query-time                = 1
slow-query-log-file            = ${BASEDIR}/logs/mysql-slow.log
EOF

systemctl restart mysqld
systemctl status  mysqld

echo "done!"
exit 0
