#!/bin/bash

deploy_dir='/usr/local/lnmp'
extension_dir='/usr/local/lnmp/php71/lib/php/extensions/no-debug-non-zts-20160303/'

do_install()
{
    if [ ! -e ./igbinary-2.0.1.tgz ];then
        wget http://pecl.php.net/get/igbinary-2.0.1.tgz
    fi
    if ! test -f ${extension_dir}/igbinary.so; then
        tar zxvf igbinary-2.0.1.tgz
        cd igbinary-2.0.1
        ${deploy_dir}/php71/bin/phpize
        ./configure  --enable-igbinary --with-php-config=${deploy_dir}/php71/bin/php-config
        if [ $? -eq 0 ];then
            make && make install && cd ..
            if [ $? -ne 0 ];then
                echo "igbinary install fialed"
                exit 1
            fi
        else
            exit 1
        fi
    fi

    if ! test -f ${extension_dir}/mongodb.so; then
        if [ ! -e ./mongodb-1.2.9.tgz ];then
             wget http://pecl.php.net/get/mongodb-1.2.9.tgz 
        fi
        tar zxvf mongodb-1.2.9.tgz
        cd mongodb-1.2.9
        ${deploy_dir}/php71/bin/phpize
        ./configure --with-php-config=${deploy_dir}/php71/bin/php-config --enable-mongodb
        if [ "$?" -eq 0 ];then
            make && make install && cd ..
            if [ $? -ne 0 ];then
                echo "mongodb install fialed"
                exit 1
            fi
        else
            exit 1
        fi
    fi
    if ! test -f ${extension_dir}/redis.so; then
        if [ ! -e ./redis-3.1.3.tgz ];then
            wget http://pecl.php.net/get/redis-3.1.3.tgz 
        fi
        tar zxvf redis-3.1.3.tgz
        cd redis-3.1.3
        ${deploy_dir}/php71/bin/phpize
        ./configure --with-php-config=${deploy_dir}/php71/bin/php-config --enable-redis --enable-redis-igbinary
        if [ "$?" -eq 0 ];then
            make && make install && cd ..
            if [ $? -ne 0 ];then
                echo "redis install fialed"
                exit 1
            fi
        else
            exit 1
        fi
    fi

    if ! test -d ${deploy_dir}/libmemcached; then
        if [ ! -e ./libmemcached-1.0.18.tar.gz ];then
            wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz
        fi
        tar xzf libmemcached-1.0.18.tar.gz
        cd libmemcached-1.0.18
        ${deploy_dir}/php71/bin/phpize
        ./configure --prefix=${deploy_dir}/libmemcached
        if [ $? -eq 0 ];then
            make && make install && cd ..
            if [ $? -ne 0 ];then
                echo "libmemcached install fialed"
                exit 1
            fi
        else
            exit 1
        fi
    fi

    if ! test -f ${extension_dir}/memcached.so; then
        if [ ! -e ./memcached-3.0.3.tgz ];then
            wget http://pecl.php.net/get/memcached-3.0.3.tgz 
        fi
        tar zxvf memcached-3.0.3.tgz
        cd memcached-3.0.3
        ${deploy_dir}/php71/bin/phpize
        ./configure --with-php-config=${deploy_dir}/php71/bin/php-config  --enable-memcached --with-libmemcached-dir=${deploy_dir}/libmemcached
        if [ "$?" -eq 0 ];then
            make && make install && cd ..
            if [ $? -ne 0 ];then
                echo "memcached install fialed"
                exit 1
            fi
        else
            exit 1
        fi
    fi

    if ! test -f ${extension_dir}/apcu.so; then
        if [ ! -e ./apcu-5.1.8.tgz ];then
            wget http://pecl.php.net/get/apcu-5.1.8.tgz
        fi
        tar zxvf apcu-5.1.8.tgz
        cd apcu-5.1.8
        ${deploy_dir}/php71/bin/phpize
        ./configure --with-php-config=${deploy_dir}/php71/bin/php-config  --enable-apcu
        if [ "$?" -eq 0 ];then
            make && make install && cd ..
            if [ $? -ne 0 ];then
                echo "apcu install fialed"
                exit 1
            fi
        else
            exit 1
        fi
    fi
}

do_install
